package com.springapp.mvc.cleanCode;

/**
 * Created by yjhan on 15. 7. 2..
 */
public enum ErrorCode {
    UNEXPECTED_ARGUMENT, MISSING_STRING, INVALID_INTEGER, MISSING_INTEGER, INVALID_DOUBLE, MISSING_DOUBLE, INVALID_ARGUMENT_NAME, INVALID_ARGUMENT_FORMAT, OK
}
